apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeployRi05
  labels:
    app: autodeployRi05
  namespace: namespace-workflow-1710363297756
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeployRi05
  template:
    metadata:
      labels:
        app: autodeployRi05
    spec:
      containers:
        - name: autodeployRi05
          image: acrworkflow1710363297756.azurecr.io/image-workflow-1710363297756:latest
          ports:
            - containerPort: 5000