apiVersion: v1
kind: Service
metadata:
  name: autodeployRi05
  namespace: namespace-workflow-1710363297756
spec:
  type: LoadBalancer
  selector:
    app: autodeployRi05
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000